package com.example.sparePartsSetup;

import com.common.share.CommonButton;
import com.common.share.FocusMoveByEnter;
import com.common.share.MessageBox;
import com.common.share.MessageBox.ButtonType;
import com.common.share.SessionBean;
import com.common.share.SessionFactoryUtil;
import com.common.share.TextRead;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Component;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Window;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.swing.BorderFactory;

import org.hibernate.Session;
import org.hibernate.Transaction;

import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Window.Notification;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
public class RawItemSubCategory extends Window 
{
	private AbsoluteLayout mainLayout;
	private Label lblSubCategoryID;
	private TextRead trSubcategoryId;
	private Label lblSubCategoryName;
	private TextField txtSubcategoryName;
	private Label lblCategoryName;
	private ComboBox cmbCategoryName ;
	private NativeButton nbCategory;
	private Label lblline;
	private Label lblCategoryType;
	private ComboBox cmbcategoryType;

	CommonButton button = new CommonButton("New", "Save", "Edit", "", "Refresh", "Find", "", "","","Exit");

	private TextField txtSubCategoryID = new TextField();

	private SessionBean sessionBean;
	boolean isUpdate=false;
	ArrayList<Component> allComp = new ArrayList<Component>();

	private String findSubGroupId = "";

	public RawItemSubCategory(SessionBean sessionBean) 
	{
		this.sessionBean=sessionBean;
		this.setCaption("RAW ITEM SUB CATEGORY :: " + sessionBean.getCompany());
		this.setResizable(false);

		buildMainLayout();
		setContent(mainLayout);

		btnIni(true);
		componentIni(true);

		//cmbCategoryValueAdd();
		setEventAction();
		authencationCheck();
		categoryType();
	}

	private void authencationCheck()
	{
		if(sessionBean.isSubmitable())
		{
			button.btnSave.setVisible(true);
		}
		else
		{
			button.btnSave.setVisible(false);
		}
		if(sessionBean.isUpdateable())
		{
			button.btnEdit.setVisible(true);
		}
		else
		{
			button.btnEdit.setVisible(false);
		}
		if(sessionBean.isDeleteable())
		{
			button.btnDelete.setVisible(true);
		}
		else
		{
			button.btnDelete.setVisible(false);
		}
	}

	private void focusEnter()
	{
		allComp.add(txtSubcategoryName);
		allComp.add(cmbCategoryName);

		allComp.add(button.btnNew);
		allComp.add(button.btnSave);
		allComp.add(button.btnEdit);
		allComp.add(button.btnRefresh);
		allComp.add(button.btnFind);
		allComp.add(button.btnExit);

		new FocusMoveByEnter(this,allComp);
	}

	public void setEventAction()
	{
		button.btnNew.addListener( new Button.ClickListener() 
		{
			public void buttonClick(ClickEvent event) 
			{
				focusEnter();
				txtSubcategoryName.focus();
				newButtonEvent();
			}
		});

		button.btnEdit.addListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				if(sessionBean.isUpdateable()){
					updateButtonEvent();
					focusEnter();
					txtSubcategoryName.focus();
				}else{
					getParent().showNotification("Warning,","You have not Proper Authentication to Edit.", Notification.TYPE_WARNING_MESSAGE);
				}
			}
		});

		button.btnSave.addListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				if(sessionBean.isUpdateable()){
					if(!txtSubcategoryName.getValue().toString().isEmpty()){
						saveButtonEvent();
					}else{
						getParent().showNotification("Warning,","Enter Sub Category Name",Notification.TYPE_WARNING_MESSAGE);
					}
				}else{
					getParent().showNotification("Warning,","You have not Proper Authentication to Save.", Notification.TYPE_WARNING_MESSAGE);
				}
			}
		});

		button.btnFind.addListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				findButtonEvent();
			}
		});

		button.btnRefresh.addListener(new Button.ClickListener() 
		{
			public void buttonClick(ClickEvent event) {
				refreshButtonEvent();
				cmbCategoryValueAdd();
			}
		});

		button.btnExit.addListener( new Button.ClickListener() 
		{
			public void buttonClick(ClickEvent event) 
			{
				close();
			}
		});

		nbCategory.addListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				System.out.println("Category Form");
				gradeFormLink();				
			}
		});
		
		
		cmbcategoryType.addListener(new ValueChangeListener() {
			
			
			public void valueChange(ValueChangeEvent event) 
			{
				
				  if(cmbcategoryType.getValue()!=null)
				  {
					  cmbCategoryValueAdd();  
				  }
			}
		});
		
		
	}

	private void findButtonEvent() 
	{
		Window win = new RawItemSubCategoryFind(sessionBean, txtSubCategoryID);
		win.addListener(new Window.CloseListener() 
		{
			public void windowClose(CloseEvent e) 
			{
				if (txtSubCategoryID.getValue().toString().length() > 0)
				{
					txtClear();
					findInitialise(txtSubCategoryID.getValue().toString());
				}
			}
		});

		this.getParent().addWindow(win);
	}

	private void findInitialise(String txtSubCatogoryId) 
	{
		Transaction tx = null;
		try 
		{
			Session session = SessionFactoryUtil.getInstance().getCurrentSession();
			tx = session.beginTransaction();
			
			String query="";
			query=" select iSubCategoryID,vSubCategoryName,vCategoryType,iCategoryID,SubGroup_Id from tbRawItemSubCategory Where iSubCategoryID = '"+txtSubCatogoryId+"'  ";

			List led = session.createSQLQuery(query).list();

			if (led.iterator().hasNext()) 
			{
				Object[] element = (Object[]) led.iterator().next();

				trSubcategoryId.setValue(element[0]);
				txtSubcategoryName.setValue(element[1]);
				cmbcategoryType.setValue(element[2].toString());
				cmbCategoryName.setValue(element[3]);

				findSubGroupId = element[4].toString();
			}
		}
		catch (Exception exp) 
		{
			this.getParent().showNotification("Error", exp + "",Notification.TYPE_ERROR_MESSAGE);
			tx.rollback();
		}
	}

	public void gradeFormLink()
	{
		Window win = new RawItemCategory(sessionBean);

		win.setStyleName("cwindow");
		win.setModal(true);
		win.addListener(new Window.CloseListener() 
		{
			public void windowClose(CloseEvent e) 
			{
				cmbCategoryData();
				System.out.println("Category Form");
			}
		});
		this.getParent().addWindow(win);
	}

	private void cmbCategoryData()
	{
		try
		{
			Session session = SessionFactoryUtil.getInstance().getCurrentSession();
			Transaction tx = session.beginTransaction();
			String query = "Select iCategoryCode, vCategoryName from tbRawItemCategory";
			System.out.println(query);

			List list = session.createSQLQuery(query).list();

			for(Iterator iter = list.iterator(); iter.hasNext();)
			{
				Object[] element = (Object[]) iter.next();
				if (element[0] != null)
				{
					cmbCategoryName.addItem(element[0]);
					cmbCategoryName.setItemCaption(element[0], (String) element[1]);			
				}
			}
		}
		catch (Exception ex) {
			this.getParent().showNotification("Error",ex.toString(), Notification.TYPE_ERROR_MESSAGE);
		}
	}

	private void updateButtonEvent()
	{
		if(!txtSubcategoryName.getValue().toString().isEmpty())
		{
			isUpdate = true;
			btnIni(false);
			componentIni(false);
			trSubcategoryId.setEnabled(false);
		}
		else
		{
			this.getParent().showNotification("Update Failed","There are no data for update.",Notification.TYPE_WARNING_MESSAGE);
		}
	}

	private void refreshButtonEvent() 
	{
		isUpdate=false;
		componentIni(true);
		btnIni(true);
		txtClear();
	}

	public void updateData() 
	{
		Transaction tx = null;
		try
		{
			Session session = SessionFactoryUtil.getInstance().getCurrentSession();
			tx = session.beginTransaction();

			String updateQuery = "Update tbRawItemSubCategory set" +
					" vSubCategoryName = '"+txtSubcategoryName.getValue().toString().trim()+"'," +
					" iCategoryID=(Select iCategoryCode From tbRawItemCategory where  iCategoryCode like '"+cmbCategoryName.getValue()+"')," +
					" Group_Id = (Select Group_Id From tbRawItemCategory where iCategoryCode='"+cmbCategoryName.getValue()+"') ," +
					" vUserName ='"+sessionBean.getUserName()+"'," +
					" vUserIP='"+sessionBean.getUserIp()+"'," +
					" vCategoryType='"+cmbcategoryType.getValue()+"', "+
					" dtEntryTime= CURRENT_TIMESTAMP where" +
					" iSubCategoryID = '"+trSubcategoryId.getValue().toString().trim()+"'";

			/*String sql = "UPDATE tbSub_Group set " +
					" Sub_Group_Name = '"+txtSubcategoryName.getValue().toString().trim()+"' ," +
					" Group_Id = (Select Group_Id From tbRawItemCategory where Group_Id='"+cmbCategoryName.getValue()+"') ," +
					" userIp = '"+sessionBean.getUserIp()+"', " +
					" userId = '"+sessionBean.getUserId()+"', " +
					" entryTime = CURRENT_TIMESTAMP" +
					" where Sub_Group_Id = '"+findSubGroupId+"' ";*/

			session.createSQLQuery(updateQuery).executeUpdate();
			//session.createSQLQuery(sql).executeUpdate();

			System.out.println("updateQuery : "+updateQuery);

			tx.commit();
			this.getParent().showNotification("Update successfully.");
			cmbCategoryValueAdd();
		}
		catch(Exception exp)
		{
			this.getParent().showNotification("Error",exp.toString(),Notification.TYPE_ERROR_MESSAGE);
			tx.rollback();
		}	
	}

	private void saveButtonEvent() 
	{
		if(cmbcategoryType.getValue()!=null)
		{
			if(cmbCategoryName.getValue()!=null)
			{
				if(isUpdate)
				{
					final MessageBox mb = new MessageBox(getParent(), "Are you sure?", MessageBox.Icon.QUESTION, "Do you want to update product information?", new MessageBox.ButtonConfig(MessageBox.ButtonType.YES, "Yes"), new MessageBox.ButtonConfig(MessageBox.ButtonType.NO, "No"));
					mb.show(new MessageBox.EventListener()
					{
						public void buttonClicked(ButtonType buttonType)
						{
							if(buttonType == ButtonType.YES)
							{
								mb.buttonLayout.getComponent(0).setEnabled(false);
								updateData();
								button.btnNew.focus();
								isUpdate=false;
								componentIni(true);
								txtClear();
								btnIni(true);
								mb.close();
							}
						}
					});		
				}
				else
				{
					final MessageBox mb = new MessageBox(getParent(), "Are you sure?", MessageBox.Icon.QUESTION, "Do you want to Save information?", new MessageBox.ButtonConfig(MessageBox.ButtonType.YES, "Yes"), new MessageBox.ButtonConfig(MessageBox.ButtonType.NO, "No"));
					mb.show(new MessageBox.EventListener()
					{
						public void buttonClicked(ButtonType buttonType)
						{
							if(buttonType == ButtonType.YES)
							{
								mb.buttonLayout.getComponent(0).setEnabled(false);
								insertData();
								btnIni(true);
								cmbCategoryValueAdd();
								componentIni(true);
								txtClear();
								btnIni(true);
								button.btnNew.focus();
								mb.close();
							}
						}
					});		
				}
			}

			else
			{
				this.getParent().showNotification("Warning :", "Please select Category Name", Notification.TYPE_WARNING_MESSAGE);
				cmbCategoryName.focus();
			}	
		}
		
		else
		{
			this.getParent().showNotification("Warning :", "Please select Category Type", Notification.TYPE_WARNING_MESSAGE);
			cmbCategoryName.focus();
		}
		
		
	}

	private void insertData()
	{
		Transaction tx = null;
		String subGroupId = "";
		try
		{
			Session session = SessionFactoryUtil.getInstance().getCurrentSession();
			tx = session.beginTransaction();

			List lst = session.createSQLQuery("select 0 zero,('S'+ISNULL((SELECT cast((max(substring(Sub_Group_Id,2,len(Group_Id)-1))+1)" +
					" as VARCHAR) FROM tbSub_Group),101)) id").list();

			if (lst.iterator().hasNext()) 
			{
				Object[] element = (Object[]) lst.iterator().next();

				subGroupId = element[1].toString();
			}

			String insertQuery = "Insert Into tbRawItemSubCategory (iSubCategoryID,vSubCategoryName,iCategoryID," +
					" Group_Id,SubGroup_Id,vUserName,vUserIP,dtEntryTime,vCategoryType) values" +
					" ('"+trSubcategoryId.getValue().toString().trim()+"'," +
					" '"+txtSubcategoryName.getValue().toString().trim()+"'," +
					"( select iCategoryCode from tbRawItemCategory where iCategoryCode like '"+cmbCategoryName.getValue()+"')," +
					" (Select Group_Id From tbRawItemCategory where iCategoryCode='"+cmbCategoryName.getValue()+"')," +
					" '"+subGroupId+"'," +
					" '"+sessionBean.getUserName()+"'," +
					" '"+sessionBean.getUserIp()+"',CURRENT_TIMESTAMP,'"+cmbcategoryType.getValue()+"')";

			/*String sql = "INSERT INTO tbSub_Group(Sub_Group_Id,Sub_Group_Name,Group_Id,userId,userIp,entryTime)" +
					" VALUES( '"+subGroupId+"', " +
					" '"+txtSubcategoryName.getValue()+"'," +
					" (Select Group_Id From tbRawItemCategory where Group_Id='"+cmbCategoryName.getValue()+"')," +
					" '"+sessionBean.getUserId()+"'," +
					" '"+sessionBean.getUserIp()+"',CURRENT_TIMESTAMP)";

			session.createSQLQuery(sql).executeUpdate();*/
			session.createSQLQuery(insertQuery).executeUpdate();

			tx.commit();

			this.getParent().showNotification("All information Save successfully.");
			btnIni(true);
		}
		catch(Exception exp)
		{
			this.getParent().showNotification("Error",exp+"",Notification.TYPE_ERROR_MESSAGE);
			tx.rollback();
		}
	}

	private void newButtonEvent() 
	{
		componentIni(false);
		btnIni(false);
		txtClear();
		newBtnData(1);
		cmbCategoryValueAdd();
		trSubcategoryId.setEnabled(false);	
	}

	
	public void cmbCategoryValueAdd()
	{
		cmbCategoryName.removeAllItems();
		Transaction tx = null;
		try{
			Session session = SessionFactoryUtil.getInstance().getCurrentSession();
			tx = session.beginTransaction();
			List list = session.createSQLQuery("select iCategoryCode,vCategoryName  from tbRawItemCategory where vCategoryType like '"+cmbcategoryType.getValue()+"' ").list();

			for(Iterator iter=list.iterator();iter.hasNext();)
			{
				Object[] element = (Object[]) iter.next();
				cmbCategoryName.addItem(element[0]);
				cmbCategoryName.setItemCaption(element[0], (String) element[1]);
			}
		}
		catch(Exception exp)
		{
			this.getParent().showNotification("Error here",exp+"",Notification.TYPE_ERROR_MESSAGE);
		}
	}
	
	
	public void categoryType()
	{
		cmbcategoryType.removeAllItems();
		Transaction tx = null;
		try{
			Session session = SessionFactoryUtil.getInstance().getCurrentSession();
			tx = session.beginTransaction();
			List list = session.createSQLQuery("select  distinct 0, vCategoryType  from tbRawItemCategory").list();

			for(Iterator iter=list.iterator();iter.hasNext();)
			{
				Object[] element = (Object[]) iter.next();
				cmbcategoryType.addItem(element[1]);
				cmbcategoryType.setItemCaption(element[1], (String) element[1]);
			}
		}
		catch(Exception exp)
		{
			this.getParent().showNotification("Error here",exp+"",Notification.TYPE_ERROR_MESSAGE);
		}
	}
	
	
	
	

	public void newBtnData(int flag)
	{
		if(txtSubcategoryName.getValue().toString().isEmpty() || flag==1)
		{
			Transaction tx = null;
			try
			{
				Session session = SessionFactoryUtil.getInstance().getCurrentSession();
				tx = session.beginTransaction();
				String sql = "Select isnull(max(iSubCategoryID)+1,1) as subcat from tbRawItemSubCategory";
				Iterator iter = session.createSQLQuery(sql).list().iterator();
				int num = 0;

				if (iter.hasNext())
				{
					num = Integer.parseInt(iter.next().toString());
					trSubcategoryId.setValue(num);
				}
			}
			catch(Exception ex)
			{
				this.getParent().showNotification("Error",ex+"",Notification.TYPE_ERROR_MESSAGE);
			}
		}
	}

	public void txtClear()
	{
		trSubcategoryId.setValue("");
		txtSubcategoryName.setValue("");
		cmbCategoryName.setValue(null);
		cmbcategoryType.setValue(null);
	}

	private void componentIni(boolean b) 
	{
		lblSubCategoryID.setEnabled(!b);
		trSubcategoryId.setEnabled(!b);		

		lblSubCategoryName.setEnabled(!b);
		txtSubcategoryName.setEnabled(!b);

		lblCategoryName.setEnabled(!b);
		cmbCategoryName.setEnabled(!b);
		cmbcategoryType.setEnabled(!b);

		lblline.setEnabled(!b);
		lblCategoryType.setEnabled(!b);

		nbCategory.setEnabled(!b);
	}

	private void btnIni(boolean t)
	{
		button.btnNew.setEnabled(t);
		button.btnEdit.setEnabled(t);
		button.btnSave.setEnabled(!t);
		button.btnRefresh.setEnabled(!t);
		button.btnDelete.setEnabled(t);
		button.btnFind.setEnabled(t);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() 
	{
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("530px");
		mainLayout.setHeight("230px");
		mainLayout.setMargin(false);

		/*// top-level component properties
		setWidth("540px");
		setHeight("290px");*/

		// lblCategoryId
		lblSubCategoryID = new Label();
		lblSubCategoryID.setImmediate(false);
		lblSubCategoryID.setWidth("-1px");
		lblSubCategoryID.setHeight("-1px");
		lblSubCategoryID.setValue(" Sub Category ID:");
		mainLayout.addComponent(lblSubCategoryID, "top:30.0px;left:43.0px;");

		// categoryRead
		trSubcategoryId= new TextRead();
		trSubcategoryId.setImmediate(false);
		trSubcategoryId.setWidth("101px");
		trSubcategoryId.setHeight("24px");
		mainLayout.addComponent(trSubcategoryId, "top:28.0px;left:160.0px;");

		// labCategoryName
		lblSubCategoryName = new Label();
		lblSubCategoryName.setImmediate(false);
		lblSubCategoryName.setWidth("-1px");
		lblSubCategoryName.setHeight("-1px");
		lblSubCategoryName.setValue(" SubCategory Name :");
		mainLayout.addComponent(lblSubCategoryName, "top:57.0px;left:20.0px;");

		// txtCategoryname
		txtSubcategoryName = new TextField();
		txtSubcategoryName.setImmediate(false);
		txtSubcategoryName.setWidth("280px");
		txtSubcategoryName.setHeight("-1px");
		txtSubcategoryName.setSecret(false);
		mainLayout.addComponent(txtSubcategoryName, "top:54.0px;left:160.0px;");
		
		lblCategoryType = new Label();
		lblCategoryType.setImmediate(false);
		lblCategoryType.setWidth("-1px");
		lblCategoryType.setHeight("-1px");
		lblCategoryType.setValue(" Item Type :");
		mainLayout.addComponent(lblCategoryType, "top:83.0px;left:45.0px;");

		cmbcategoryType= new ComboBox();
		cmbcategoryType.setImmediate(true);
		cmbcategoryType.setWidth("280px");
		cmbcategoryType.setNullSelectionAllowed(true);
		cmbcategoryType.setNewItemsAllowed(false);
		cmbcategoryType.setFilteringMode(ComboBox.FILTERINGMODE_CONTAINS);
		mainLayout.addComponent(cmbcategoryType, "top:80.0px;left:160.0px;");
		
		
		lblCategoryName = new Label();
		lblCategoryName.setImmediate(false);
		lblCategoryName.setWidth("-1px");
		lblCategoryName.setHeight("-1px");
		lblCategoryName.setValue(" Category Name:");
		mainLayout.addComponent(lblCategoryName, "top:109.0px;left:45.0px;");

		cmbCategoryName= new ComboBox();
		cmbCategoryName.setImmediate(true);
		cmbCategoryName.setWidth("280px");
		cmbCategoryName.setNullSelectionAllowed(true);
		cmbCategoryName.setNewItemsAllowed(false);
		cmbCategoryName.setFilteringMode(ComboBox.FILTERINGMODE_CONTAINS);
		mainLayout.addComponent(cmbCategoryName, "top:106.0px;left:160.0px;");

		nbCategory = new NativeButton();
		nbCategory.setIcon(new ThemeResource("../icons/add.png"));
		nbCategory.setStyleName("nbCategory");
        nbCategory.setImmediate(true);
		nbCategory.setWidth("32px");
		nbCategory.setHeight("24px");
		mainLayout.addComponent(nbCategory,"top:106.0px;left:450.0px;");

		lblline= new Label();
		lblline.setImmediate(false);
		lblline.setWidth("-1px");
		lblline.setHeight("-1px");
		lblline.setValue("_________________________________________________________________________");
		mainLayout.addComponent(lblline, "top:140.0px;left:10.0px;");

		mainLayout.addComponent(button, "top:180.0px;left:12.0px;");

		return mainLayout;
	}
	
}
