package com.example.sparePartsSetup;

import com.common.share.CommonButton;
import com.common.share.FocusMoveByEnter;
import com.common.share.MessageBox;
import com.common.share.MessageBox.ButtonType;
import com.common.share.SessionBean;
import com.common.share.SessionFactoryUtil;
import com.common.share.TextRead;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Component;
import com.vaadin.ui.Label;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Window;

import java.net.InetAddress;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;

import javax.swing.ButtonGroup;

import org.hibernate.Session;
import org.hibernate.Transaction;

import com.vaadin.terminal.gwt.server.WebApplicationContext;
import com.vaadin.terminal.gwt.server.WebBrowser;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Window.Notification;

public class SpareItemCategory extends Window 
{
	SessionBean sessionBean;

	private AbsoluteLayout mainLayout;
	private TextField txtCategoryname;
	private Label labCategoryName;
	private TextRead categoryRead;
	private Label lblCategoryId;
	private Label lbltype;
	private OptionGroup type;
	//private List <String> Categorytype=Arrays.asList(new String[]{"Raw Material","Packing Material","Ink", "Spare Parts","Chemical","Others"});
//	private List <String> Categorytype=Arrays.asList(new String[]{"Spare Parts"});
	
	private String findGroupId = "";
	boolean isUpdate=false;
	boolean isFind=false;
	private Label lblline;
	CommonButton button = new CommonButton("New", "Save", "Edit", "", "Refresh", "Find", "", "","","Exit");

	private TextField txtCategoryID = new TextField();
	ArrayList<Component> allComp = new ArrayList<Component>();

	public SpareItemCategory(SessionBean sessionBean) 
	{
		this.sessionBean=sessionBean;
		buildMainLayout();
		setContent(mainLayout);
		this.setResizable(false);
		
		this.setCaption("SPARE PARTS CATEGORY :: " + sessionBean.getCompany());
		
		btnIni(true);
		componentIni(true);
		setEventAction();
		focusEnter();
		
		button.btnNew.focus();
		authencationCheck();
	}

	private void authencationCheck()
	{
		if(sessionBean.isSubmitable())
		{
			button.btnSave.setVisible(true);
		}
		else
		{
			button.btnSave.setVisible(false);
		}
		if(sessionBean.isUpdateable())
		{
			button.btnEdit.setVisible(true);
		}
		else
		{
			button.btnEdit.setVisible(false);
		}
		if(sessionBean.isDeleteable())
		{
			button.btnDelete.setVisible(true);
		}
		else
		{
			button.btnDelete.setVisible(false);
		}
	}

	private void focusEnter()
	{
		allComp.add(txtCategoryname);

		allComp.add(button.btnNew);
		allComp.add(button.btnSave);
		allComp.add(button.btnEdit);
		allComp.add(button.btnRefresh);
		allComp.add(button.btnFind);
		allComp.add(button.btnExit);

		new FocusMoveByEnter(this,allComp);
	}

	public void setEventAction()
	{
		button.btnNew.addListener( new Button.ClickListener() 
		{
			public void buttonClick(ClickEvent event) 
			{
				newButtonEvent();
			}
		});

		button.btnEdit.addListener(new Button.ClickListener()
		{
			public void buttonClick(ClickEvent event)
			{
				if(sessionBean.isUpdateable())
				{
					updateButtonEvent();
					txtCategoryname.focus();
				}
				else
				{
					getParent().showNotification("You are not Permitted to Update",Notification.TYPE_WARNING_MESSAGE);
				}
			}
		});

		button.btnSave.addListener(new Button.ClickListener()
		{
			public void buttonClick(ClickEvent event)
			{
				if(sessionBean.isSubmitable())
				{
					saveButtonEvent();
				}
				else
				{
					getParent().showNotification("You are not Permitted to Save",Notification.TYPE_WARNING_MESSAGE);
				}
			}
		});

		button.btnFind.addListener(new Button.ClickListener()
		{
			public void buttonClick(ClickEvent event)
			{
				isFind=true;
				txtClear();
				findButtonEvent();
			}
		});

		button.btnRefresh.addListener(new Button.ClickListener()
		{
			public void buttonClick(ClickEvent event)
			{
				refreshButtonEvent();
			}
		});

		button.btnExit.addListener( new Button.ClickListener() 
		{
			public void buttonClick(ClickEvent event) 
			{
				close();
			}
		});
		txtCategoryname.addListener(new ValueChangeListener() 
		{
			public void valueChange(ValueChangeEvent event) 
			{
				Transaction tx = null;
				Session session = SessionFactoryUtil.getInstance().getCurrentSession();
				tx = session.beginTransaction();
				
				if(!txtCategoryname.getValue().toString().isEmpty())
				{
					List list = session.createSQLQuery("select * from tbRawItemCategory where vCategoryName like '"+txtCategoryname.getValue().toString().trim()+"'").list();
					
					if(list.isEmpty() )
					{
					  System.out.println("Rack");	
					}
					else
					{
						if(!isFind)
						{
							 showNotification("Warning! Category Name Already Exists :" +txtCategoryname.getValue().toString());
							 txtCategoryname.setValue("");	
						}
					 }
				}
			}
		});
	}

	private void findButtonEvent() 
	{
		Window win = new SpareItemCategoryFind(sessionBean, txtCategoryID);
		win.addListener(new Window.CloseListener() 
		{
			public void windowClose(CloseEvent e) 
			{
				if (txtCategoryID.getValue().toString().length() > 0)
				{
					txtClear();
					findInitialise(txtCategoryID.getValue().toString());
				}
			}
		});

		this.getParent().addWindow(win);
	}

	private void findInitialise(String txtCategoryId) 
	{
		Transaction tx = null;
		String strtype="";
		try 
		{
			Session session = SessionFactoryUtil.getInstance().getCurrentSession();
			tx = session.beginTransaction();

			List led = session.createSQLQuery("Select iCategoryCode,vCategoryName,Group_Id from tbRawItemCategory Where iCategoryCode = '"+txtCategoryId+"'").list();

			if (led.iterator().hasNext()) 
			{
				Object[] element = (Object[]) led.iterator().next();

				categoryRead.setValue(element[0]);
				txtCategoryname.setValue(element[1]);

				findGroupId = element[2].toString();
				//type.select(element[3].toString());
			}
		}
		catch (Exception exp) 
		{
			showNotification("Error", exp + "",Notification.TYPE_ERROR_MESSAGE);
			tx.rollback();
		}
	}

	private void refreshButtonEvent()
	{
		isUpdate=false;
		componentIni(true);
		btnIni(true);
		txtClear();
	}

	private void saveButtonEvent() 
	{
		if(!txtCategoryname.getValue().toString().isEmpty())
		{
			if(isUpdate)
			{
				final MessageBox mb = new MessageBox(getParent(), "Are you sure?", MessageBox.Icon.QUESTION, "Do you want to update product information?", new MessageBox.ButtonConfig(MessageBox.ButtonType.YES, "Yes"), new MessageBox.ButtonConfig(MessageBox.ButtonType.NO, "No"));
				mb.show(new MessageBox.EventListener()
				{
					public void buttonClicked(ButtonType buttonType)
					{
						if(buttonType == ButtonType.YES)
						{
							mb.buttonLayout.getComponent(0).setEnabled(false);
							updateData();

							txtClear();
							componentIni(true);
							btnIni(true);
							isUpdate=false;
							isFind=false;
							button.btnNew.focus();
							isUpdate=false;
							
						}
					}
				});		
			}
			else
			{
				final MessageBox mb = new MessageBox(getParent(), "Are you sure?", MessageBox.Icon.QUESTION, "Do you want to Save information?", new MessageBox.ButtonConfig(MessageBox.ButtonType.YES, "Yes"), new MessageBox.ButtonConfig(MessageBox.ButtonType.NO, "No"));
				mb.show(new MessageBox.EventListener()
				{
					public void buttonClicked(ButtonType buttonType)
					{
						if(buttonType == ButtonType.YES)
						{
							mb.buttonLayout.getComponent(0).setEnabled(false);
							insertData();
							btnIni(true);
							//cmbValueAdd();
							componentIni(true);
							txtClear();
							isUpdate = false;
							isFind=false;
							btnIni(true);
							button.btnNew.focus();
							
						}
					}
				});		
			}
		}

		else{
			this.getParent().showNotification("Warning :", "Please select Category Name", Notification.TYPE_WARNING_MESSAGE);
			txtCategoryname.focus();
		}
	}


	private void insertData()
	{
		String groupId= "";
		String strcattype="";
		Transaction tx = null;
		try
		{
			Session session = SessionFactoryUtil.getInstance().getCurrentSession();
			tx = session.beginTransaction();
			
			/*if(type.isSelected("Raw Material"))
				strcattype="Raw Material";
			if(type.isSelected("Packing Material"))
				strcattype="Packing Material";
			if(type.isSelected("Spare Parts"))
				strcattype="Spare Parts";*/

			/*List lst = session.createSQLQuery("select 0 zero,('G'+ISNULL((SELECT cast((max(substring(Group_Id,2,len(Group_Id)-1))+1)" +
					" as VARCHAR) FROM TbMain_Group),101)) id").list();

			if (lst.iterator().hasNext()) 
			{
				Object[] element = (Object[]) lst.iterator().next();

				groupId = element[1].toString();
			}

			String sql = "INSERT INTO TbMain_Group(Group_Id,Group_Name,Head_Id,userId,userIp,entryTime) VALUES" +
					" ('"+groupId+"' ," +
					" '"+txtCategoryname.getValue()+"','A5'," +
					" '"+sessionBean.getUserId()+"','"+sessionBean.getUserIp()+"',CURRENT_TIMESTAMP)";*/

			String insertQuery = "Insert Into tbRawItemCategory (iCategoryCode,vCategoryName,Group_Id,vUserName,vUserIP,dtEntryTime,vCategoryType,vFlag)" +
					" values ('"+categoryRead.getValue()+"','"+txtCategoryname.getValue()+"','"+categoryRead.getValue()+"', " +
					" '"+sessionBean.getUserName()+"','"+sessionBean.getUserIp()+"',CURRENT_TIMESTAMP,'Spare Parts','New')";

			System.out.println("insertQuery : "+insertQuery);
			//System.out.println("group : "+sql);

			//session.createSQLQuery(sql).executeUpdate();
			session.createSQLQuery(insertQuery).executeUpdate();
			tx.commit();

			this.getParent().showNotification("All Information Saved successfully.");
			btnIni(true);
		}
		catch(Exception exp)
		{
			this.getParent().showNotification("Error ",exp+"",Notification.TYPE_ERROR_MESSAGE);
			tx.rollback();
		}
	}

	public void updateData() 
	{
		Transaction tx = null;
		String strcattype="";
		try
		{
			Session session = SessionFactoryUtil.getInstance().getCurrentSession();
			tx = session.beginTransaction();
			strcattype="Spare Parts";
		/*	if(type.isSelected("Raw Material"))
				strcattype="Raw Material";
			if(type.isSelected("Packing Material"))
				strcattype="Packing Material";
			if(type.isSelected("Spare Parts"))
				strcattype="Spare Parts";
			if(type.isSelected("Chemical"))
				strcattype="Chemical";
			if(type.isSelected("Ink"))
				strcattype="Ink";
			if(type.isSelected("Others"))
				strcattype="Others";*/
			
			WebApplicationContext context = ((WebApplicationContext) getApplication().getContext());
			WebBrowser webBrowser = context.getBrowser();
			sessionBean.setUserIp(webBrowser.getAddress());    

			InetAddress inetAddress =InetAddress.getByName(webBrowser.getAddress().toString());//get the host Inet using ip

			String updateQuery = "Update tbRawItemCategory set " +
					" vCategoryName = '"+txtCategoryname.getValue().toString().trim()+"', " +
					" vUserName ='"+sessionBean.getUserName()+"', " +
					" vUserIP='"+inetAddress.getHostName()+"', " +
					" dtEntryTime= CURRENT_TIMESTAMP, vCategoryType = '"+strcattype+"' ,vFlag='New'  where iCategoryCode = '"+categoryRead.getValue()+"'";

			/*String sql = "UPDATE TbMain_Group set " +
					" Group_Name = '"+txtCategoryname.getValue()+"' ," +
					" userIp = '"+sessionBean.getUserIp()+"', " +
					" userId = '"+sessionBean.getUserId()+"', " +
					" entryTime = CURRENT_TIMESTAMP" +
					" where Group_Id = '"+findGroupId+"' ";*/

			session.createSQLQuery(updateQuery).executeUpdate();
			//session.createSQLQuery(sql).executeUpdate();

			System.out.println("updateQuery : "+updateQuery);

			tx.commit();
			this.getParent().showNotification("Updated successfully.");
			//cmbValueAdd();
		}
		catch(Exception exp)
		{
			this.getParent().showNotification("Error",exp+"",Notification.TYPE_ERROR_MESSAGE);
			tx.rollback();
		}	
	}

	private void updateButtonEvent()
	{
		if(!txtCategoryname.getValue().toString().isEmpty())
		{
			isUpdate = true;
			btnIni(false);
			componentIni(false);//Enable(true);
			categoryRead.setEnabled(false);
		}
		else
		{
			this.getParent().showNotification("Update Failed","There are no data for update.",Notification.TYPE_WARNING_MESSAGE);
		}
	}

	private void newButtonEvent() 
	{
		componentIni(false);
		btnIni(false);
		txtClear();
		newBtnData(1);
		isFind=false;
		txtCategoryname.focus();
		categoryRead.setEnabled(false);
	}

	public void newBtnData(int flag)
	{
		if(txtCategoryname.getValue().toString().isEmpty() || flag==1)
		{
			Transaction tx = null;
			try{
				Session session = SessionFactoryUtil.getInstance().getCurrentSession();
				tx = session.beginTransaction();
				String sql = "Select isnull(max(iCategoryCode)+1,1) as cat from tbRawItemCategory";
				Iterator iter = session.createSQLQuery(sql).list().iterator();
				int num = 0;
				if (iter.hasNext()) {
					num = Integer.parseInt(iter.next().toString());
					categoryRead.setValue(num);
				}
			}
			catch(Exception ex){
				this.getParent().showNotification("Error",ex+"",Notification.TYPE_ERROR_MESSAGE);
			}
		}
		else{

		}
	}

	public void txtClear()
	{
		txtCategoryname.setValue("");
		categoryRead.setValue("");
	}


	private void componentIni(boolean b) 
	{
		lblline.setEnabled(!b);
		categoryRead.setEnabled(!b);
		txtCategoryname.setEnabled(!b);
	//	type.setEnabled(!b);
	}

	private void btnIni(boolean t)
	{
		button.btnNew.setEnabled(t);
		button.btnEdit.setEnabled(t);
		button.btnSave.setEnabled(!t);
		button.btnFind.setEnabled(t);
		button.btnRefresh.setEnabled(!t);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() 
	{
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		/*mainLayout.setWidth("530px");
		mainLayout.setHeight("240px");*/
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("580px");
		setHeight("230px");

		// lblCategoryId
		lblCategoryId = new Label();
		lblCategoryId.setImmediate(false);
		lblCategoryId.setWidth("-1px");
		lblCategoryId.setHeight("-1px");
		lblCategoryId.setValue("Category ID:");
		mainLayout.addComponent(lblCategoryId, "top:40.0px;left:45.0px;");

		// categoryRead
		categoryRead = new TextRead();
		categoryRead.setImmediate(false);
		categoryRead.setWidth("101px");
		categoryRead.setHeight("24px");
		mainLayout.addComponent(categoryRead, "top:34.0px;left:160.0px;");

		// labCategoryName
		labCategoryName = new Label();
		labCategoryName.setImmediate(false);
		labCategoryName.setWidth("-1px");
		labCategoryName.setHeight("-1px");
		labCategoryName.setValue("Category Name :");
		mainLayout.addComponent(labCategoryName, "top:65.0px;left:45.0px;");

		// txtCategoryname
		txtCategoryname = new TextField();
		txtCategoryname.setImmediate(false);
		txtCategoryname.setWidth("300px");
		txtCategoryname.setHeight("-1px");
		txtCategoryname.setSecret(false);
		mainLayout.addComponent(txtCategoryname, "top:63.0px;left:160.0px;");
		
		lbltype=new Label();
		lbltype.setCaption("Type: ");
		lbltype.setImmediate(false);
		lbltype.setWidth("-1px");
		lbltype.setHeight("-1px");
		//mainLayout.addComponent(lbltype, "top:112.0px; left:45.0px;");
		
/*		type=new OptionGroup("", Categorytype);
		type.setStyleName("horizontal");
		type.select("Raw Material");
		type.setImmediate(true);
		mainLayout.addComponent(type, "top:96.0px; left:100.0px;");*/

		lblline= new Label();
		lblline.setImmediate(false);
		lblline.setWidth("-1px");
		lblline.setHeight("-1px");
		lblline.setValue("__________________________________________________________________________");
		mainLayout.addComponent(lblline, "top:115.0px;left:10.0px;");

		mainLayout.addComponent(button, "top:135.0px;left:12.0px;");

		return mainLayout;
	}

}
