package database.hibernate;

// Generated Feb 23, 2011 3:39:26 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbAuthentication generated by hbm2java
 */
@Entity
@Table(name = "tbAuthentication", schema = "dbo", catalog = "broker")
public class TbAuthentication implements java.io.Serializable {

	private int sl;
	private Integer userId;
	private String menuId;
	private Date insertTime;
	private Integer createBy;
	private String menuCaption;

	public TbAuthentication() {
	}

	public TbAuthentication(int sl) {
		this.sl = sl;
	}

	public TbAuthentication(int sl, Integer userId, String menuId,
			Date insertTime, Integer createBy, String menuCaption) {
		this.sl = sl;
		this.userId = userId;
		this.menuId = menuId;
		this.insertTime = insertTime;
		this.createBy = createBy;
		this.menuCaption = menuCaption;
	}

	@Id
	@Column(name = "sl", unique = true, nullable = false)
	public int getSl() {
		return this.sl;
	}

	public void setSl(int sl) {
		this.sl = sl;
	}

	@Column(name = "userId")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "menuId", length = 50)
	public String getMenuId() {
		return this.menuId;
	}

	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "insertTime", length = 23)
	public Date getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	@Column(name = "createBy")
	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	@Column(name = "menuCaption", length = 100)
	public String getMenuCaption() {
		return this.menuCaption;
	}

	public void setMenuCaption(String menuCaption) {
		this.menuCaption = menuCaption;
	}

}
