package database.hibernate;

// Generated Jan 11, 2011 10:26:51 AM by Hibernate Tools 3.3.0.GA

/**
 * TbLedger generated by hbm2java
 */
public class TbLedger implements java.io.Serializable {

	private String ledgerId;
	private String ledgerName;
	private Integer creationYear;
	private String parentId;
	private String createFrom;

	public TbLedger() {
	}

	public TbLedger(String ledgerId) {
		this.ledgerId = ledgerId;
	}

	public TbLedger(String ledgerId, String ledgerName, Integer creationYear,
			String parentId, String createFrom) {
		this.ledgerId = ledgerId;
		this.ledgerName = ledgerName;
		this.creationYear = creationYear;
		this.parentId = parentId;
		this.createFrom = createFrom;
	}

	public String getLedgerId() {
		return this.ledgerId;
	}

	public void setLedgerId(String ledgerId) {
		this.ledgerId = ledgerId;
	}

	public String getLedgerName() {
		return this.ledgerName;
	}

	public void setLedgerName(String ledgerName) {
		this.ledgerName = ledgerName;
	}

	public Integer getCreationYear() {
		return this.creationYear;
	}

	public void setCreationYear(Integer creationYear) {
		this.creationYear = creationYear;
	}

	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public String getCreateFrom() {
		return this.createFrom;
	}

	public void setCreateFrom(String createFrom) {
		this.createFrom = createFrom;
	}

}
