package database.hibernate;

// Generated Jan 11, 2011 10:26:51 AM by Hibernate Tools 3.3.0.GA

/**
 * TbLedgerOpBalanceId generated by hbm2java
 */
public class TbLedgerOpBalanceId implements java.io.Serializable {

	private String ledgerId;
	private int opYear;

	public TbLedgerOpBalanceId() {
	}

	public TbLedgerOpBalanceId(String ledgerId, int opYear) {
		this.ledgerId = ledgerId;
		this.opYear = opYear;
	}

	public String getLedgerId() {
		return this.ledgerId;
	}

	public void setLedgerId(String ledgerId) {
		this.ledgerId = ledgerId;
	}

	public int getOpYear() {
		return this.opYear;
	}

	public void setOpYear(int opYear) {
		this.opYear = opYear;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbLedgerOpBalanceId))
			return false;
		TbLedgerOpBalanceId castOther = (TbLedgerOpBalanceId) other;

		return ((this.getLedgerId() == castOther.getLedgerId()) || (this
				.getLedgerId() != null && castOther.getLedgerId() != null && this
				.getLedgerId().equals(castOther.getLedgerId())))
				&& (this.getOpYear() == castOther.getOpYear());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLedgerId() == null ? 0 : this.getLedgerId().hashCode());
		result = 37 * result + this.getOpYear();
		return result;
	}

}
