package database.hibernate;

// Generated Feb 23, 2011 3:39:26 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TbLogin generated by hbm2java
 */
@Entity
@Table(name = "tbLogin", schema = "dbo", catalog = "broker", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class TbLogin implements java.io.Serializable {

	private int userId;
	private String name;
	private String pass;
	private Date createTime;
	private Integer createBy;
	private Integer isAdmin;
	private Integer isInsertable;
	private Integer isUpdateable;
	private Integer isDeleteable;
	private Integer isActive;

	public TbLogin() {
	}

	public TbLogin(int userId, String name) {
		this.userId = userId;
		this.name = name;
	}

	public TbLogin(int userId, String name, String pass, Date createTime,
			Integer createBy, Integer isAdmin, Integer isInsertable,
			Integer isUpdateable, Integer isDeleteable, Integer isActive) {
		this.userId = userId;
		this.name = name;
		this.pass = pass;
		this.createTime = createTime;
		this.createBy = createBy;
		this.isAdmin = isAdmin;
		this.isInsertable = isInsertable;
		this.isUpdateable = isUpdateable;
		this.isDeleteable = isDeleteable;
		this.isActive = isActive;
	}

	@Id
	@Column(name = "userId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "name", unique = true, nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "pass", length = 100)
	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 23)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "createBy")
	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	@Column(name = "isAdmin")
	public Integer getIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(Integer isAdmin) {
		this.isAdmin = isAdmin;
	}

	@Column(name = "isInsertable")
	public Integer getIsInsertable() {
		return this.isInsertable;
	}

	public void setIsInsertable(Integer isInsertable) {
		this.isInsertable = isInsertable;
	}

	@Column(name = "isUpdateable")
	public Integer getIsUpdateable() {
		return this.isUpdateable;
	}

	public void setIsUpdateable(Integer isUpdateable) {
		this.isUpdateable = isUpdateable;
	}

	@Column(name = "isDeleteable")
	public Integer getIsDeleteable() {
		return this.isDeleteable;
	}

	public void setIsDeleteable(Integer isDeleteable) {
		this.isDeleteable = isDeleteable;
	}

	@Column(name = "isActive")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

}
