package database.hibernate;

// Generated Jan 11, 2011 10:26:51 AM by Hibernate Tools 3.3.0.GA

/**
 * TbNarrationList generated by hbm2java
 */
public class TbNarrationList implements java.io.Serializable {

	private String narrationId;
	private String narration;
	private String voucherType;
	private Integer slNo;

	public TbNarrationList() {
	}

	public TbNarrationList(String narrationId) {
		this.narrationId = narrationId;
	}

	public TbNarrationList(String narrationId, String narration,
			String voucherType, Integer slNo) {
		this.narrationId = narrationId;
		this.narration = narration;
		this.voucherType = voucherType;
		this.slNo = slNo;
	}

	public String getNarrationId() {
		return this.narrationId;
	}

	public void setNarrationId(String narrationId) {
		this.narrationId = narrationId;
	}

	public String getNarration() {
		return this.narration;
	}

	public void setNarration(String narration) {
		this.narration = narration;
	}

	public String getVoucherType() {
		return this.voucherType;
	}

	public void setVoucherType(String voucherType) {
		this.voucherType = voucherType;
	}

	public Integer getSlNo() {
		return this.slNo;
	}

	public void setSlNo(Integer slNo) {
		this.slNo = slNo;
	}

}
