package database.hibernate;

// Generated Jan 11, 2011 10:26:51 AM by Hibernate Tools 3.3.0.GA

/**
 * TbSubGroup generated by hbm2java
 */
public class TbSubGroup implements java.io.Serializable {

	private String subGroupId;
	private String subGroupName;
	private String groupId;

	public TbSubGroup() {
	}

	public TbSubGroup(String subGroupId) {
		this.subGroupId = subGroupId;
	}

	public TbSubGroup(String subGroupId, String subGroupName, String groupId) {
		this.subGroupId = subGroupId;
		this.subGroupName = subGroupName;
		this.groupId = groupId;
	}

	public String getSubGroupId() {
		return this.subGroupId;
	}

	public void setSubGroupId(String subGroupId) {
		this.subGroupId = subGroupId;
	}

	public String getSubGroupName() {
		return this.subGroupName;
	}

	public void setSubGroupName(String subGroupName) {
		this.subGroupName = subGroupName;
	}

	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

}
