package database.hibernate;

// Generated Jan 11, 2011 10:26:51 AM by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * VwChequeRegisterId generated by hbm2java
 */
public class VwChequeRegisterId implements java.io.Serializable {

	private String voucherNo;
	private Date date;
	private String narration;
	private BigDecimal drAmount;
	private BigDecimal crAmount;
	private String vouchertype;
	private String transactionWith;
	private String chequeNo;
	private Date chequeDate;
	private String partyAccountDetails;
	private String bankId;
	private Date clearanceDate;
	private String bankName;
	private String branchName;
	private String ledgerId;
	private String ledgerName;
	private int mrNo;

	public VwChequeRegisterId() {
	}

	public VwChequeRegisterId(String voucherNo, Date date, String narration,
			BigDecimal drAmount, BigDecimal crAmount, String vouchertype,
			String chequeNo, Date chequeDate, String bankId, String ledgerId,
			int mrNo) {
		this.voucherNo = voucherNo;
		this.date = date;
		this.narration = narration;
		this.drAmount = drAmount;
		this.crAmount = crAmount;
		this.vouchertype = vouchertype;
		this.chequeNo = chequeNo;
		this.chequeDate = chequeDate;
		this.bankId = bankId;
		this.ledgerId = ledgerId;
		this.mrNo = mrNo;
	}

	public VwChequeRegisterId(String voucherNo, Date date, String narration,
			BigDecimal drAmount, BigDecimal crAmount, String vouchertype,
			String transactionWith, String chequeNo, Date chequeDate,
			String partyAccountDetails, String bankId, Date clearanceDate,
			String bankName, String branchName, String ledgerId,
			String ledgerName, int mrNo) {
		this.voucherNo = voucherNo;
		this.date = date;
		this.narration = narration;
		this.drAmount = drAmount;
		this.crAmount = crAmount;
		this.vouchertype = vouchertype;
		this.transactionWith = transactionWith;
		this.chequeNo = chequeNo;
		this.chequeDate = chequeDate;
		this.partyAccountDetails = partyAccountDetails;
		this.bankId = bankId;
		this.clearanceDate = clearanceDate;
		this.bankName = bankName;
		this.branchName = branchName;
		this.ledgerId = ledgerId;
		this.ledgerName = ledgerName;
		this.mrNo = mrNo;
	}

	public String getVoucherNo() {
		return this.voucherNo;
	}

	public void setVoucherNo(String voucherNo) {
		this.voucherNo = voucherNo;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getNarration() {
		return this.narration;
	}

	public void setNarration(String narration) {
		this.narration = narration;
	}

	public BigDecimal getDrAmount() {
		return this.drAmount;
	}

	public void setDrAmount(BigDecimal drAmount) {
		this.drAmount = drAmount;
	}

	public BigDecimal getCrAmount() {
		return this.crAmount;
	}

	public void setCrAmount(BigDecimal crAmount) {
		this.crAmount = crAmount;
	}

	public String getVouchertype() {
		return this.vouchertype;
	}

	public void setVouchertype(String vouchertype) {
		this.vouchertype = vouchertype;
	}

	public String getTransactionWith() {
		return this.transactionWith;
	}

	public void setTransactionWith(String transactionWith) {
		this.transactionWith = transactionWith;
	}

	public String getChequeNo() {
		return this.chequeNo;
	}

	public void setChequeNo(String chequeNo) {
		this.chequeNo = chequeNo;
	}

	public Date getChequeDate() {
		return this.chequeDate;
	}

	public void setChequeDate(Date chequeDate) {
		this.chequeDate = chequeDate;
	}

	public String getPartyAccountDetails() {
		return this.partyAccountDetails;
	}

	public void setPartyAccountDetails(String partyAccountDetails) {
		this.partyAccountDetails = partyAccountDetails;
	}

	public String getBankId() {
		return this.bankId;
	}

	public void setBankId(String bankId) {
		this.bankId = bankId;
	}

	public Date getClearanceDate() {
		return this.clearanceDate;
	}

	public void setClearanceDate(Date clearanceDate) {
		this.clearanceDate = clearanceDate;
	}

	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	public String getLedgerId() {
		return this.ledgerId;
	}

	public void setLedgerId(String ledgerId) {
		this.ledgerId = ledgerId;
	}

	public String getLedgerName() {
		return this.ledgerName;
	}

	public void setLedgerName(String ledgerName) {
		this.ledgerName = ledgerName;
	}

	public int getMrNo() {
		return this.mrNo;
	}

	public void setMrNo(int mrNo) {
		this.mrNo = mrNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwChequeRegisterId))
			return false;
		VwChequeRegisterId castOther = (VwChequeRegisterId) other;

		return ((this.getVoucherNo() == castOther.getVoucherNo()) || (this
				.getVoucherNo() != null && castOther.getVoucherNo() != null && this
				.getVoucherNo().equals(castOther.getVoucherNo())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null
						&& castOther.getDate() != null && this.getDate()
						.equals(castOther.getDate())))
				&& ((this.getNarration() == castOther.getNarration()) || (this
						.getNarration() != null
						&& castOther.getNarration() != null && this
						.getNarration().equals(castOther.getNarration())))
				&& ((this.getDrAmount() == castOther.getDrAmount()) || (this
						.getDrAmount() != null
						&& castOther.getDrAmount() != null && this
						.getDrAmount().equals(castOther.getDrAmount())))
				&& ((this.getCrAmount() == castOther.getCrAmount()) || (this
						.getCrAmount() != null
						&& castOther.getCrAmount() != null && this
						.getCrAmount().equals(castOther.getCrAmount())))
				&& ((this.getVouchertype() == castOther.getVouchertype()) || (this
						.getVouchertype() != null
						&& castOther.getVouchertype() != null && this
						.getVouchertype().equals(castOther.getVouchertype())))
				&& ((this.getTransactionWith() == castOther
						.getTransactionWith()) || (this.getTransactionWith() != null
						&& castOther.getTransactionWith() != null && this
						.getTransactionWith().equals(
								castOther.getTransactionWith())))
				&& ((this.getChequeNo() == castOther.getChequeNo()) || (this
						.getChequeNo() != null
						&& castOther.getChequeNo() != null && this
						.getChequeNo().equals(castOther.getChequeNo())))
				&& ((this.getChequeDate() == castOther.getChequeDate()) || (this
						.getChequeDate() != null
						&& castOther.getChequeDate() != null && this
						.getChequeDate().equals(castOther.getChequeDate())))
				&& ((this.getPartyAccountDetails() == castOther
						.getPartyAccountDetails()) || (this
						.getPartyAccountDetails() != null
						&& castOther.getPartyAccountDetails() != null && this
						.getPartyAccountDetails().equals(
								castOther.getPartyAccountDetails())))
				&& ((this.getBankId() == castOther.getBankId()) || (this
						.getBankId() != null && castOther.getBankId() != null && this
						.getBankId().equals(castOther.getBankId())))
				&& ((this.getClearanceDate() == castOther.getClearanceDate()) || (this
						.getClearanceDate() != null
						&& castOther.getClearanceDate() != null && this
						.getClearanceDate()
						.equals(castOther.getClearanceDate())))
				&& ((this.getBankName() == castOther.getBankName()) || (this
						.getBankName() != null
						&& castOther.getBankName() != null && this
						.getBankName().equals(castOther.getBankName())))
				&& ((this.getBranchName() == castOther.getBranchName()) || (this
						.getBranchName() != null
						&& castOther.getBranchName() != null && this
						.getBranchName().equals(castOther.getBranchName())))
				&& ((this.getLedgerId() == castOther.getLedgerId()) || (this
						.getLedgerId() != null
						&& castOther.getLedgerId() != null && this
						.getLedgerId().equals(castOther.getLedgerId())))
				&& ((this.getLedgerName() == castOther.getLedgerName()) || (this
						.getLedgerName() != null
						&& castOther.getLedgerName() != null && this
						.getLedgerName().equals(castOther.getLedgerName())))
				&& (this.getMrNo() == castOther.getMrNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getVoucherNo() == null ? 0 : this.getVoucherNo().hashCode());
		result = 37 * result
				+ (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result
				+ (getNarration() == null ? 0 : this.getNarration().hashCode());
		result = 37 * result
				+ (getDrAmount() == null ? 0 : this.getDrAmount().hashCode());
		result = 37 * result
				+ (getCrAmount() == null ? 0 : this.getCrAmount().hashCode());
		result = 37
				* result
				+ (getVouchertype() == null ? 0 : this.getVouchertype()
						.hashCode());
		result = 37
				* result
				+ (getTransactionWith() == null ? 0 : this.getTransactionWith()
						.hashCode());
		result = 37 * result
				+ (getChequeNo() == null ? 0 : this.getChequeNo().hashCode());
		result = 37
				* result
				+ (getChequeDate() == null ? 0 : this.getChequeDate()
						.hashCode());
		result = 37
				* result
				+ (getPartyAccountDetails() == null ? 0 : this
						.getPartyAccountDetails().hashCode());
		result = 37 * result
				+ (getBankId() == null ? 0 : this.getBankId().hashCode());
		result = 37
				* result
				+ (getClearanceDate() == null ? 0 : this.getClearanceDate()
						.hashCode());
		result = 37 * result
				+ (getBankName() == null ? 0 : this.getBankName().hashCode());
		result = 37
				* result
				+ (getBranchName() == null ? 0 : this.getBranchName()
						.hashCode());
		result = 37 * result
				+ (getLedgerId() == null ? 0 : this.getLedgerId().hashCode());
		result = 37
				* result
				+ (getLedgerName() == null ? 0 : this.getLedgerName()
						.hashCode());
		result = 37 * result + this.getMrNo();
		return result;
	}

}
