package database.hibernate;

// Generated 17-Apr-2011 15:02:43 by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VwVoucher generated by hbm2java
 */
@Entity
@Table(name = "vwVoucher", schema = "dbo", catalog = "account")
public class VwVoucher implements java.io.Serializable {

	private VwVoucherId id;

	public VwVoucher() {
	}

	public VwVoucher(VwVoucherId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "autoId", column = @Column(name = "AutoId", nullable = false)),
			@AttributeOverride(name = "voucherNo", column = @Column(name = "Voucher_No", nullable = false, length = 50)),
			@AttributeOverride(name = "date", column = @Column(name = "Date", nullable = false, length = 23)),
			@AttributeOverride(name = "ledgerId", column = @Column(name = "Ledger_Id", nullable = false, length = 50)),
			@AttributeOverride(name = "narration", column = @Column(name = "Narration", nullable = false, length = 250)),
			@AttributeOverride(name = "drAmount", column = @Column(name = "DrAmount", nullable = false, scale = 4)),
			@AttributeOverride(name = "crAmount", column = @Column(name = "CrAmount", nullable = false, scale = 4)),
			@AttributeOverride(name = "vouchertype", column = @Column(name = "vouchertype", nullable = false, length = 50)),
			@AttributeOverride(name = "transactionWith", column = @Column(name = "TransactionWith", length = 250)),
			@AttributeOverride(name = "costId", column = @Column(name = "costId", length = 50)),
			@AttributeOverride(name = "userId", column = @Column(name = "userId")),
			@AttributeOverride(name = "userIp", column = @Column(name = "userIp", length = 50)),
			@AttributeOverride(name = "entryTime", column = @Column(name = "entryTime", length = 23)) })
	public VwVoucherId getId() {
		return this.id;
	}

	public void setId(VwVoucherId id) {
		this.id = id;
	}

}
