package com.example.RecycledModuleReport;

import java.awt.Checkbox;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;

import org.hibernate.Session;
import org.hibernate.Transaction;

import com.common.share.CommonButton;
import com.common.share.FocusMoveByEnter;
import com.common.share.ReportViewer;
import com.common.share.SessionBean;
import com.common.share.SessionFactoryUtil;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.DateField;
import com.vaadin.ui.InlineDateField;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.Window;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Window.Notification;

public class RptRecycledItemInfo extends Window {

	private AbsoluteLayout mainLayout;
	private ComboBox  cmbCategoryName;
	private Label lblCategoryName;
	private Label lblItemName;
	private ComboBox  cmbItemName;
	private Label lblsubcategoryName;
	private ComboBox cmbsubcategoryName;
	private CheckBox chkAllsubcategory;
	private Label lblline;
	private NativeButton previewButton = new NativeButton("Preview");
	private NativeButton exitButton = new NativeButton("Exit");
	SessionBean sessionBean;
	private CheckBox chkAllPartyName;
	private CheckBox chkAllCategory;
	

	
	private CheckBox chkpdf,chkother;
	boolean type=false;

	public  RptRecycledItemInfo(SessionBean sessionBean,String str) {
		this.sessionBean = sessionBean;
		buildMainLayout();
		setContent(mainLayout);
		this.setResizable(false);
		this.setCaption("STOCK SUMMARY ::  "+ sessionBean.getCompany());
		cmbCategoryName.focus();
		Component ob[]={cmbItemName,cmbsubcategoryName,previewButton};
		new FocusMoveByEnter(this, ob);
		allButtonAction();
		categoryData(); 

		cmbsubcategoryName.setEnabled(false);
		chkAllsubcategory.setEnabled(false);

		cmbItemName.setEnabled(false);
		chkAllPartyName.setEnabled(false);
	}


	private void categoryData()
	{
		Session session = SessionFactoryUtil.getInstance().getCurrentSession();
		Transaction tx;
		tx = session.beginTransaction();
		String query = "select Distinct iCategoryId,vCategoryName from tbRecycleItemInfo ";

		System.out.println(query);

		cmbCategoryName.removeAllItems();
		List list = session.createSQLQuery(query).list();		
		for(Iterator iter = list.iterator(); iter.hasNext();)
		{
			Object[] element = (Object[]) iter.next();
			cmbCategoryName.addItem(element[0]);
			cmbCategoryName.setItemCaption(element[0], element[1].toString());
		}
	}
	
	private void subcategorydataload()
	{
		Session session = SessionFactoryUtil.getInstance().getCurrentSession();
		Transaction tx;
		tx = session.beginTransaction();
		
		String categoryType="";
		String Category="";
		
		if(chkAllCategory.booleanValue())
		{
			Category="%";
		}
		if(cmbCategoryName.getValue()!=null)
		{
			Category=cmbCategoryName.getValue().toString();
		}
		
		String query = "select Distinct iSubCategoryId,vSubCategoryName from tbRecycleItemInfo where iCategoryId like '"+Category+"' ";

		System.out.println(query);

		cmbsubcategoryName.removeAllItems();
		List list = session.createSQLQuery(query).list();
		if(!list.isEmpty())
		{
			for(Iterator iter = list.iterator(); iter.hasNext();)
			{
				Object[] element = (Object[]) iter.next();
				cmbsubcategoryName.addItem(element[0]);
				cmbsubcategoryName.setItemCaption(element[0], element[1].toString());
			}
		}
	}

	private void itemNameDateLoad()
	{
		Session session = SessionFactoryUtil.getInstance().getCurrentSession();
		Transaction tx;
		tx = session.beginTransaction();
		String category="", subcategory="";
		if(chkAllCategory.booleanValue()==true)
		{
			category="%";
		}
		else
		{
			category=cmbCategoryName.getValue().toString();
		}
		if(chkAllsubcategory.booleanValue()==true)
		{
			subcategory="%";}
		else
		{
			subcategory=cmbsubcategoryName.getValue().toString();
		}
				
		String query= " select Distinct vItemCode,vItemName from tbRecycleItemInfo "
				+ "where iCategoryId like '"+category+"' and "
				+ "iSubCategoryId like '"+subcategory+"'";
		System.out.println(query);

		List<?> list = session.createSQLQuery(query).list();
		cmbItemName.removeAllItems();
		for(Iterator iter = list.iterator(); iter.hasNext();)
		{
			Object[] element = (Object[]) iter.next();
			cmbItemName.addItem(element[0]);
			cmbItemName.setItemCaption(element[0], element[1].toString());
		}
	}

	
	private void allButtonAction()
	{
		chkpdf.addListener(new ValueChangeListener()
		{
			public void valueChange(ValueChangeEvent event)
			{
				if(chkpdf.booleanValue()==true)
				{
					chkother.setValue(false);
					type=true;
				}
				
				else
				{
					chkother.setValue(true);
				//	type=false;
				}
		}

		});
		chkother.addListener(new ValueChangeListener()
		{

			public void valueChange(ValueChangeEvent event)
			{
				if(chkother.booleanValue()==true)									
				{
					chkpdf.setValue(false);
					type=true;
				}
				else
				{
					chkpdf.setValue(true);				
				}
			}
		});

		cmbCategoryName.addListener(new ValueChangeListener() 
		{
			public void valueChange(ValueChangeEvent event) 
			{
				if(cmbCategoryName.getValue()!=null)
				{
					cmbsubcategoryName.setEnabled(true);
					chkAllsubcategory.setEnabled(true);

					cmbItemName.setEnabled(false);
					chkAllPartyName.setEnabled(false);

					cmbItemName.setValue(null);
					chkAllPartyName.setValue(false);

					subcategorydataload();
				}
				else
				{
					cmbsubcategoryName.setEnabled(false);
					chkAllsubcategory.setEnabled(false);
					
					cmbItemName.setValue(null);
					chkAllPartyName.setValue(false);
					
					cmbItemName.setEnabled(false);
					chkAllPartyName.setEnabled(false);

					cmbItemName.setValue(null);
					chkAllPartyName.setValue(false);
					cmbsubcategoryName.removeAllItems();
					categoryData();
				}
			}
		});
		
		cmbsubcategoryName.addListener(new ValueChangeListener()
		{
			public void valueChange(ValueChangeEvent event)
			{				
				if(cmbsubcategoryName.getValue()!=null)
				{		
					cmbItemName.setEnabled(true);
					chkAllPartyName.setEnabled(true);
					itemNameDateLoad(); 			
				}			
				else{
					cmbItemName.setEnabled(false);
					chkAllPartyName.setEnabled(false);

					cmbItemName.setValue(null);
					chkAllPartyName.setValue(false);
					
					cmbItemName.removeAllItems();
					subcategorydataload();
				}
			}
		});
		
		
		chkAllsubcategory.addListener(new ValueChangeListener()
		{
			public void valueChange(ValueChangeEvent event)
			{
				boolean bv = chkAllsubcategory.booleanValue();
				if(bv==true)
				{
					cmbsubcategoryName.setValue(null);
					cmbsubcategoryName.setEnabled(false);

					cmbItemName.setEnabled(true);
					chkAllPartyName.setEnabled(true);
					itemNameDateLoad();
					}	
					else{
						cmbsubcategoryName.setEnabled(true);

						cmbsubcategoryName.setValue(null);
						chkAllsubcategory.setValue(false);

						cmbItemName.setEnabled(false);
						chkAllPartyName.setEnabled(false);

						cmbItemName.setValue(null);
						chkAllPartyName.setValue(false);
						cmbItemName.removeAllItems();
						subcategorydataload();
					}	
			}
		});

	
		previewButton.addListener(new Button.ClickListener() 
		{
			public void buttonClick(ClickEvent event) {
				if(cmbCategoryName.getValue()!=null || chkAllCategory.booleanValue()==true)
				{

					if(cmbItemName.getValue()!=null || chkAllPartyName.booleanValue()==true)
					{			
						
						reportShow();
					}

					else
					{
						showNotification("Select Product Name", Notification.TYPE_WARNING_MESSAGE);
					}

				}
				else
				{
					getParent().showNotification("Select Category Name", Notification.TYPE_WARNING_MESSAGE);
				}
				
			}
		});


		exitButton.addListener( new Button.ClickListener() 
		{
			public void buttonClick(ClickEvent event) 
			{
				close();
			}
		});

		chkAllPartyName.addListener(new ValueChangeListener() 
		{
			public void valueChange(ValueChangeEvent event) 
			{
				boolean bv = chkAllPartyName.booleanValue();
				if(bv==true)
				{
					cmbItemName.setValue(null);
					cmbItemName.setEnabled(false);
				}
				else{
					cmbItemName.setEnabled(true);
					if((cmbsubcategoryName.getValue()!=null || chkAllsubcategory.booleanValue()) && (cmbCategoryName.getValue()!=null || chkAllCategory.booleanValue()) )
					itemNameDateLoad();
				}
			}
		});


		chkAllCategory.addListener(new ValueChangeListener() 
		{
			public void valueChange(ValueChangeEvent event) 
			{
				boolean bv = chkAllCategory.booleanValue();
				if(bv==true)
				{
					cmbCategoryName.setValue(null);
					cmbCategoryName.setEnabled(false); 
					
					cmbsubcategoryName.setEnabled(true);
					chkAllsubcategory.setEnabled(true);

					cmbItemName.setEnabled(false);
					chkAllPartyName.setEnabled(false);

					cmbItemName.setValue(null);
					chkAllPartyName.setValue(false);
					subcategorydataload();
				}
				else{
					cmbCategoryName.setEnabled(true);
					cmbsubcategoryName.setEnabled(false);
					chkAllsubcategory.setEnabled(false);
					cmbsubcategoryName.setValue(null);
					chkAllsubcategory.setValue(false);

					cmbItemName.setEnabled(false);
					chkAllPartyName.setEnabled(false);

					cmbItemName.setValue(null);
					chkAllPartyName.setValue(false);
					cmbsubcategoryName.removeAllItems();
					categoryData();
				}
			}
		});

	}

	private void reportShow()
	{
		System.out.println("into Reportshow");
		String query=null;
		String categoryID="";
		String itemId="";
		String subcategoryID="";
		if(chkpdf.booleanValue()==true)
		{
			type= true;
		}
		else
		{
			type=false;
		}
		if(chkAllCategory.booleanValue())
		{
			categoryID ="%"; 
		}

		else
		{
			categoryID = cmbCategoryName.getValue().toString();
		}

		if(chkAllsubcategory.booleanValue())
			subcategoryID="%";
		else
			subcategoryID=cmbsubcategoryName.getValue().toString();

		if(chkAllPartyName.booleanValue())
		{
			itemId ="%";
		}
		else
		{
			itemId =cmbItemName.getValue().toString();
		}
		
		
		
		try{

			Session session = SessionFactoryUtil.getInstance().getCurrentSession();
			Transaction tx = session.beginTransaction();

			HashMap hm = new HashMap();
			hm.put("logo", sessionBean.getCompanyLogo());
			hm.put("company", sessionBean.getCompany());
			hm.put("address", sessionBean.getCompanyAddress());
			hm.put("Phone", sessionBean.getCompanyContact());
			hm.put("username", sessionBean.getUserName()+"  "+sessionBean.getUserIp());
			
			String sql= "select vItemCode,vItemName,iCategoryId,vCategoryName,iSubCategoryId,vSubCategoryName,vBaseProductId,vBaseProductName,vUnitName,vModelNo,vColor from tbRecycleItemInfo"
					+ " where iCategoryId like '"+categoryID+"' and "
					+ "iSubCategoryId like '"+subcategoryID+"' and"
					+ " vItemCode like '"+itemId+"'"; 
			
			System.out.println(query);
			hm.put("sql", sql);
			System.out.println("123");

			List lst= session.createSQLQuery(sql).list();
			if(!lst.isEmpty())
			{
				System.out.println("Trying To Do");
				Window win = new ReportViewer(hm,"report/production/RecycledModuleReport/rptRecycledItemInfo.jasper",
						this.getWindow().getApplication().getContext().getBaseDirectory()+"".replace("\\","/")+"/VAADIN/rpttmp",
						this.getWindow().getApplication().getURL()+"VAADIN/rpttmp",false,
						this.getWindow().getApplication().getURL()+"VAADIN/applet",type);				
				System.out.println("789");
				win.setCaption("Project Report");
				this.getParent().getWindow().addWindow(win);	
			}		
			else
			{
			   showNotification("Data does not exists on the given criteria.",Notification.TYPE_WARNING_MESSAGE);	
			}						
		}
		catch(Exception exp){

			this.getParent().showNotification("Error "+exp,Notification.TYPE_ERROR_MESSAGE);
		}
	}
	
	

	private AbsoluteLayout buildMainLayout() 
	{
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("520px");
		mainLayout.setHeight("180px");
		mainLayout.setMargin(false);

		//top-level component properties
		setWidth("560px");
		setHeight("230px");
		
		// lblCategoryName
		lblCategoryName = new Label();
		lblCategoryName.setImmediate(false);
		lblCategoryName.setWidth("-1px");
		lblCategoryName.setHeight("-1px");
		lblCategoryName.setValue("Category Name :");
		mainLayout.addComponent(lblCategoryName, "top:40.0px;left:45.0px;");

		// cmbCategoryName
		cmbCategoryName = new ComboBox();
		cmbCategoryName.setImmediate(true);
		cmbCategoryName.setWidth("260px");
		cmbCategoryName.setHeight("24px");
		cmbCategoryName.setNullSelectionAllowed(false);
		cmbCategoryName.setNewItemsAllowed(false);
		cmbCategoryName.setFilteringMode(ComboBox.FILTERINGMODE_CONTAINS);
		mainLayout.addComponent( cmbCategoryName, "top:38.0px;left:185.0px;");
			
		chkAllCategory = new CheckBox("");
		chkAllCategory.setCaption("All");
		chkAllCategory.setWidth("-1px");
		chkAllCategory.setHeight("24px");
		chkAllCategory.setImmediate(true);
		mainLayout.addComponent(chkAllCategory, "top:38.0px;left:445.0px;");  
		
		lblsubcategoryName = new Label();
		lblsubcategoryName.setImmediate(false);
		lblsubcategoryName.setWidth("-1px");
		lblsubcategoryName.setHeight("-1px");
		lblsubcategoryName.setValue("Sub-Category Name :");
		mainLayout.addComponent(lblsubcategoryName,  "top:66.0px;left:45.0px;"); 

		cmbsubcategoryName = new ComboBox();
		cmbsubcategoryName.setWidth("260px");
		cmbsubcategoryName.setHeight("24px");
		cmbsubcategoryName.setImmediate(true);
		cmbsubcategoryName.setNewItemsAllowed(false);
		cmbsubcategoryName.setNullSelectionAllowed(false);
		cmbsubcategoryName.setFilteringMode(ComboBox.FILTERINGMODE_CONTAINS);
		mainLayout.addComponent( cmbsubcategoryName,    "top:64.0px;left:185.0px;");  
		
		chkAllsubcategory=new CheckBox("");
		chkAllsubcategory.setCaption("All");
		chkAllsubcategory.setImmediate(true);
		chkAllsubcategory.setWidth("-1px");
		chkAllsubcategory.setHeight("24px");
		mainLayout.addComponent(chkAllsubcategory, "top:64.0px;left:445.0px;");
		
		lblItemName = new Label();
		lblItemName.setImmediate(false);
		lblItemName.setWidth("-1px");
		lblItemName.setHeight("-1px");
		lblItemName.setValue("Item Name :");
		mainLayout.addComponent(lblItemName,  "top:92.0px;left:45.0px;");  

		cmbItemName = new ComboBox();
		cmbItemName.setImmediate(true);
		cmbItemName.setWidth("260px");
		cmbItemName.setHeight("24px");
		cmbItemName.setNullSelectionAllowed(false);
		cmbItemName.setNewItemsAllowed(false);
		cmbItemName.setFilteringMode(ComboBox.FILTERINGMODE_CONTAINS);
		mainLayout.addComponent(cmbItemName,   "top:90.0px;left:185.0px;");  


		chkAllPartyName = new CheckBox("");
		chkAllPartyName.setCaption("All");
		chkAllPartyName.setWidth("-1px");
		chkAllPartyName.setHeight("24px");
		chkAllPartyName.setImmediate(true);
		mainLayout.addComponent(chkAllPartyName, "top:90.0px; left:445.0px;");

		
		chkpdf=new CheckBox("PDF");
		chkpdf.setImmediate(true);
		chkpdf.setValue(true);
		mainLayout.addComponent(chkpdf, "top:116px; left:185px");

		chkother=new CheckBox("Other");
		chkother.setImmediate(true);
		mainLayout.addComponent(chkother, "top:116px; left:245px");

		lblline = new Label();
		lblline.setImmediate(false);
		lblline.setWidth("-1px");
		lblline.setHeight("-1px");
		lblline.setValue("____________________________________________________________________________");
		mainLayout.addComponent(lblline, "top:130.0px;left:20.0px;");

		previewButton.setWidth("95px");
		previewButton.setHeight("28px");
		previewButton.setIcon(new ThemeResource("../icons/print.png"));
		mainLayout.addComponent(previewButton,"top:150.opx; left:140.0px");

		exitButton.setWidth("70px");
		exitButton.setHeight("28px");
		exitButton.setIcon(new ThemeResource("../icons/exit.png"));
		mainLayout.addComponent(exitButton,"top:150.opx; left:250.0px");

		return mainLayout;
	}
	
}
